### PR TITLE
Update Theme Actions Workflow

### PR DESCRIPTION
**Pull request by KedarMalapDev**
# Shopify Theme Preview Workflow

## Overview

This GitHub Actions workflow automates the process of creating, updating, and managing Shopify theme previews for pull requests. It provides an easy way for contributors to generate and interact with theme previews during the development process.

## Trigger Events

- Pull request events: opened, synchronized, reopened
- Issue comments: created (for manual commands)

## Key Features

1. **Automatic Preview Creation**
   - Generates a theme preview when a pull request is opened or updated
   - Checks for conflicts and relevant changes before creating/updating previews

2. **Manual Control**
   - Allows manual creation of previews using the `!preview` command in comments
   - Enables manual removal of previews using the `!remove` command

3. **Intelligent Updates**
   - Updates existing previews when new changes are pushed to the pull request
   - Skips update if no relevant theme changes are detected

4. **User Feedback**
   - Provides preview links, theme IDs, and editor URLs in pull request comments
   - Informs users if a preview already exists when `!preview` is used again
   - Notifies users about conflicts or lack of relevant changes

5. **Preview Lifecycle Management**
   - Prevents preview creation for closed or merged pull requests
   - Allows manual cleanup of previews when no longer needed

## Workflow Steps

1. **Check Theme Status**
   - Determines if a preview should be created or updated
   - Checks for existing previews and recent commands (`!preview` or `!remove`)

2. **Check for Conflicts and Relevant Changes**
   - Ensures there are no merge conflicts in the pull request
   - Verifies that there are relevant changes to the theme files

3. **Deploy Theme Preview**
   - Creates a new preview theme or updates an existing one on Shopify
   - Generates preview URLs and editor links

4. **Comment on Pull Request**
   - Provides feedback to users based on the outcome of the preview process
   - Includes relevant links and instructions for further actions

## Usage

- **Automatic**: The workflow runs automatically on new pull requests and updates
- **Manual**: Contributors can use `!preview` to create/update and `!remove` to delete previews

## Note

This workflow requires proper setup of Shopify API credentials and GitHub secrets. Ensure all necessary permissions and tokens are configured in the repository settings.

## Workflow File

The workflow is defined in `.github/workflows/shopify-theme-preview.yml`.

### CODE REVIEW

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!remove

**Comment by mihir-bombay-studio** [comment]
!preview

**Comment by KedarMalapDev** [comment]
!preview

**Pull request closed without merging**
