### PR TITLE
Reviews Section

### PR DESCRIPTION
**Pull request by KedarMalapDev**

### CODE REVIEW

**Comment by mihir-bombay-studio** [comment]
!preview

**Comment by mihir-bombay-studio** [comment]
!unlock-preview

**Comment by KedarMalapDev** [comment]
!unlock-preview

**Comment by mihir-bombay-studio** [comment]
Design
image

Section
image

Arrow position, font sizes and margins seem to be incorrect
The animation while sliding seem to be missing and the active dot doesn't change when changing slides

**Comment by KedarMalapDev** [comment]
Ok I will redesign asap.

**Comment by KedarMalapDev** [comment]
!preview

**Pull request closed without merging**
