### PR TITLE
Fixed Scroll Issue and Updated Hide Scroll Class of Collection Section

### PR DESCRIPTION
**Pull request by dd-anish**

### CODE REVIEW

**Comment by dd-anish** [comment]
Basically we have 2 options, either to have 100 view height or to have an aspect square of left col image matching to the height of righ col div (2 blocks height)

**Option 1**

https://github.com/user-attachments/assets/c359a4db-237e-4f26-9fdf-ba3033401155

**Option 2**

https://github.com/user-attachments/assets/cac76d78-f56b-4a65-b22e-8b3523240a72


_Current Code of the PR has the 100vh Style Code_

**Comment by dd-anish** [comment]
Updated the left col image as Aspect Square Option because in figma design they have styled in that way.

image

[Figma Link](https://www.figma.com/design/7YNkrtNVfbWxiREw1KSzEt/eCommerce---Flower-Delivery-website-%7C-UI-%26-UX-%7C-Ui-kit-%7C-Template-(Community)?node-id=815-6681&t=PD9Dc1ayop6rwjU1-0)

Preview URL - https://theme-skeleton.myshopify.com/collections/new-snowboards

**Comment by mihir-bombay-studio** [comment]
Option 2 seems to be better

**Comment by dd-anish** [comment]
> Option 2 seems to be better

Yes, so I updated the code of PR but due to Footer I am getting conflicts so I will update the code again

**Comment by mihir-bombay-studio** [comment]
!preview

**Pull request merged**
